CREATE TABLE ROLES
(
    ID            VARCHAR(255) PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP    NOT NULL
);

ALTER TABLE ROLES
    ADD CONSTRAINT UQ_ROLES UNIQUE (NAME);