CREATE TABLE ROLES_TEAMS_USERS
(
    ID            VARCHAR(255) PRIMARY KEY,
    ROLE_ID       VARCHAR(255) NOT NULL,
    TEAM_ID       VARCHAR(255) NOT NULL,
    USER_ID       VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP    NOT NULL
);

ALTER TABLE ROLES_TEAMS_USERS
    ADD CONSTRAINT FK_ROLES
        FOREIGN KEY (ROLE_ID)
            REFERENCES ROLES (ID);

ALTER TABLE ROLES_TEAMS_USERS
    ADD CONSTRAINT UQ_ROLES_TEAMS_USERS UNIQUE (ROLE_ID, USER_ID);
